---
- name: Ensure PostgreSQL packages are installed.
  dnf:
    name: "@postgresql:{{ postgresql_version }}"
    state: present
    enablerepo: "powertools,{{ postgresql_enablerepo | default(omit, true) }}"
    # Don't let postgresql-contrib cause the /usr/bin/python symlink
    # to be installed, which breaks later Ansible runs on Fedora 30,
    # and affects system behavior in multiple ways.
    exclude: python-unversioned-command

- name: Ensure PostgreSQL Python libraries are installed.
  dnf:
    name: "{{ postgresql_python_library }}"
    state: present
    enablerepo: "{{ postgresql_enablerepo | default(omit, true) }}"
